sudo: required
dist: trusty
language: php
git:
  depth: 5

php:
  - "7.3"

before_install:
  - sudo curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get -y install zip
  - sudo apt-get -y install sshpass

install:
  - npm install
  - composer install

before_script:
  - chmod +x ./deploy.sh

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run
  - composer test

after_success: ./deploy.sh